name: LabsPartyPlugin
main: de.bergwerklabs.party.client.bukkit.BukkitPartyClient
version: 1.0
author: freggy

depend: [LabsFrameworkSpigotCommons, LabsFrameworkSpigotChatCommons]

commands:
    party: